// src/components/Hero.tsx
import React from 'react'

const Hero:React.FC = () => {
	return (
		<div className='pt-20 pb-20'>
		<div className="flex justify-between flex-col md:flex-row space-y-6">
		<div className='flex flex-col  pl-6 justify-center'>
                  <div className="text-4xl md:text-5xl text-white font-semibold ">The Minimal <span className='text-blue-400'>Golang</span> framework</div>
		  <div className="text-7xl md:text-9xl text-purple-500 font-bold ">Minima</div>
		  <div className="text-xl md:text-2xl text-gray-400 text-left font-semibold pt-3">Framework for Go HTTP services with 0 dependencies</div>
		  
		</div>
		<div className='bg-purple-800 rounded-l-full relative z-0 pt-4 md:pt-0'>
		<img className="banner pr-6 mr-6 md:mr-18 " src={require("./img/banner.png").default} alt="minima code png" />	
		</div>
		</div>   	
		</div>
	)
}

export default Hero

// src/components/Hero.vue
<script lang="ts">
import { defineComponent } from "@vue/runtime-core";
export default defineComponent({
	name : "Hero",
	setup(){

	}
})
</script>


<template>
<div class="flex justify-center pt-8 flex-col items-center">
  <div class="text-4xl md:text-8xl text-white font-bold">The Golang framework</div>
   <div class="text-4xl md:text-8xl text-white font-bold">to scale</div>
    <div class="text-md md:text-2xl text-gray-300 text-center pt-8">Minima offers you the most minimal developer experience with everything that is needed to scale</div>
    <div class="hidden md:block md:text-2xl text-gray-300 text-center ">start using minima with your exsisting net/http projects!</div>
    <div class="flex space-x-10 pt-8">
	<button class="p-3 rounded-full text-xl font-semibold text-white bg-hero ">Documentation</button>
	<button class="p-3 rounded-full text-xl font-semibold text-white bg-gray-600">Explore utility</button>
	
    </div>
    <div class="text-sm text-gray-500 pt-8">DEVELOPED BY MINIMA CORE TEAM™</div>
 </div>
</template>
